#!/bin/bash
#
# Copyright 2014-2015 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: "v1"
kind: "Template"
metadata:
  name: hawkular-deployer
  annotations:
    description: "Template for deploying the Hawkular application"
    tags: "instant-app,hawkular,monitoring"
objects:
-
  apiVersion: v1
  kind: Pod
  metadata:
    generateName: hawkular-deployer-
  spec:
    containers:
    - image: hawkular/hawkular-deployer:latest
      name: hawkular-deployer
      env:
        - name: PROJECT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TEST_MODE
          value: ${TEST_MODE}
        - name: CASSANDRA_NODES
          value: ${CASSANDRA_NODES}
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    volumes:
    - name: empty
      emptyDir: {}
parameters:
-
  description: 'Give your instance an unique name'
  name: APP_NAME
  value: "hawkular"
-
  description: 'TEST_MODE=true to enable jdoe test account'
  name: TEST_MODE
  value: "true"
-
  description: "If set to true the deployer will try and delete all the existing components before trying to redeploy."
  name: REDEPLOY
  value: "false"
-
  description: "Comma-separate list of Cassandra nodes"
  name: CASSANDRA_NODES
  value: "127.0.0.1"
