#!/bin/bash
#
# Copyright 2014-2015 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: "Template for deploying the Hawkular application"
    tags: "instant-app,hawkular,monitoring"
objects:
-
  apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector: 
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:  
          deploymentconfig: ${APP_NAME}
        annotations:
          description: "Template for deploying the Hawkular application"
          tags: "instant-app,hawkular,monitoring"
      spec:
        containers:
        - name: hawkular
          image: hawkular/hawkular:latest
          env:
            - name: TEST_MODE
              value: "${TEST_MODE}"
            - name: CASSANDRA_NODES
              value: "${CASSANDRA_NODES}"
            - name: HAWKULAR_URL
              value: ${HAWKULAR_URL}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 240 
            timeoutSeconds: 10
        - name: cassandra
          image: cassandra:2.2
          command:
            - bash
            - "-c"
            - "sed -i 's/^start_rpc.*$/start_rpc: true/' /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh -f" 
          env:
            - name: CASSANDRA_LISTEN_ADDRESS
              value: 127.0.0.1        
