id: hawkular
kind: Template
apiVersion: v1
name: Hawkular Pod Template
description: A template to created a Hawkular instance.
metadata:
  name: hawkular
  annotations:
      description: Defines how to deploy the Hawkular application
      tags: instant-app
  labels:
    app: ${APP_NAME}
parameters:
- description: "App name"
  name: APP_NAME
  value: "hawkular"
- description: "Enable test mode (create jdoe user)"
  name: TEST_MODE
  value: "true"
- description: "Cassandra node address"
  name: CASSANDRA_NODES
  value: 127.0.0.1
- description: "External Hawkular URL for keycloak"
  name: HAWKULAR_URL
  value: localhost
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: hawkular
    labels:
      app: ${APP_NAME}
  spec:
    containers:
      - name: hawkular
        image: hawkular/hawkular:latest
        env:
          - name: TEST_MODE
            value: "${TEST_MODE}"
          - name: CASSANDRA_NODES
            value: "${CASSANDRA_NODES}"
          - name: HAWKULAR_URL
            value: ${HAWKULAR_URL}
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 240 
          timeoutSeconds: 10
      - name: cassandra
        image: cassandra:2.2
        command:
          - bash
          - "-c"
          - "sed -i 's/^start_rpc.*$/start_rpc: true/' /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh -f" 
        env:
          - name: CASSANDRA_LISTEN_ADDRESS
            value: 127.0.0.1
