apiVersion: v1
kind: Template
metadata:
  name: hawkular
  labels:
    app: ${APP_NAME}
parameters:
- description: "App name"
  name: APP_NAME 
  value: "hawkular"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: "${APP_NAME}"
    name: "${APP_NAME}"
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: "${APP_NAME}"
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
